### ISSUE TITLE
IHSV57 servos

### ISSUE THREAD

**Issue by bogus105** [tcurdt/go-servoc#1]
Hi, this is great that you've managed to talk to these servos. Got couple of them on my desk and i'd like to talk to them. Do you know what voltage should be on RS232 connector? Is it TTL (5V) or 3.3V? Where did you get tuning software for them?
And regarding to your code: would you write some know-how for begginers and non experts in linux to guide them (and me:):)) how to use your solution? Do you use these servos with EMC2(linuxcnc)? 
Thanks!

**Comment by tcurdt** [comment]
Hey @bogus105,
you need a proper RS232 for these servos - the usual UART connection is not enough.
TBH I cannot remember where I found the software. It was available for download somewhere.
It would be good know the level beginner I am facing here. Do you know how to use a terminal? What OS are you using?
My CNC plans have stalled for a while so I am not really running the servos yet.
Not sure in the end I will go for linuxcnc though.

**Comment by bogus105** [comment]
Sorry for late reply. I have communication problems on the ship:) 
Regarding 'proper UART'. What does it mean? Initially i thought i'll use by-passed arduino uno board (to use onboard usb-uart chip). The question is: what is the uart logic levels? I've read smewhere it is 3.3V! Is it true? Or it is 5V? I do not want to connect wrong one since rx/tx terminals are not isolated on iHSV57.

**Comment by tcurdt** [comment]
Read above: I said proper RS232 - not the usual UART levels.
UART uses TTL levels at 0v to Vcc (which can be 5V or 3.3V).
RS232 expects negative voltages and a level swing like -13V to +13V.

**Comment by bogus105** [comment]
Ok. I got it:) i'll use max232 for real RS232 +-15v.

**Comment by tcurdt** [comment]
Let me know if you got it to work. I failed miserably with a max232 - but I have the feeling it what broken.
